language: objective-c 
osx_image: xcode7.2
xcode_workspace: Algorithmics.xcworkspace
xcode_scheme: AlgorithmicsTest
xcode_sdk: iphonesimulator9.2

script:
- xcodebuild clean build test -workspace Algorithmic.xcworkspace -scheme AlgorithmicsTest